'use strict';

// tests for loginGoogle
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('loginGoogle', '/services/user-service/src/functions/loginGoogle.js', 'loginGoogle');

describe('loginGoogle', () => {
  it('implement tests here', async () => {
    const response = await wrapped.run();
    expect(response).to.not.be.empty;
  });
});
